CREATE TABLE BITACORA_DOC_TABLE
(
ID_BITACORA INT IDENTITY(1,1) PRIMARY KEY,
FLAG BIT  NOT NULL, 
FECHA_DOCUMENTE DATE  NOT NULL,
CEDULA VARCHAR(10)  NOT NULL,
RECIBIDO_POR VARCHAR(10)  NOT NULL,
TIPO INT  NOT NULL,
ASUNTO VARCHAR(80)  NOT NULL,
FILES VARCHAR(80)  NOT NULL,
CONSTRAINT FK_TIPO FOREIGN KEY (TIPO) REFERENCES GLOSARIO_TABLE (ID_GLOSARIO)
)

CREATE TABLE MOVIMIENTO_TABLE
(
ID_MOVIMIENTO INT IDENTITY(1,1) PRIMARY KEY,
ID_BITACORA INT  NOT NULL,
DEPARTAMENTO INT  NOT NULL,
RECIBIDO_POR VARCHAR(10)  NOT NULL,
FECHA_RECIBIDO DATE  NOT NULL,
FLAG BIT  NOT NULL,
CONSTRAINT FK_BITACORA FOREIGN KEY (ID_BITACORA) REFERENCES BITACORA_DOC_TABLE (ID_BITACORA),
CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY (DEPARTAMENTO) REFERENCES GLOSARIO_TABLE (ID_GLOSARIO)
)

CREATE TABLE GLOSARIO_TABLE
(
ID_GLOSARIO INT IDENTITY(1,1) PRIMARY KEY,
ID_FK_GLOSARIO INT  NOT NULL,
DESCRIPCION VARCHAR(80)  NOT NULL,
FLAG BIT  NOT NULL,
CONSTRAINT FK_GLOSARIO FOREIGN KEY (ID_FK_GLOSARIO) REFERENCES GLOSARIO_TABLE (ID_GLOSARIO)
);